@Student_Management_System_HostAddress = http://localhost:5242
@AccessToken = eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4NzVkYmEwLWVjMTgtNGRlZi04ZDliLWEwOTQzZDFlMTZjOSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Jyd3R2bmF6YmJiYXNmY3hlcGJzLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIzZmRmMDRmNC01YjEzLTQyNzAtODUxMy1jNmVkYWZiZDRmYjYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgzNjE2MTM3LCJpYXQiOjE3ODM2MTI1MzcsImVtYWlsIjoia2llbmR1Y2NtbEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MzYxMjUzN31dLCJzZXNzaW9uX2lkIjoiMzM0NGU5YjMtMDMzZi00MDI2LWI5MWItYjM1MGQxOGFiMTAyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.ufoSC1KbIhbWICcZ4w4qGACM7T3fXKy-__xB4yUlLWzrZ3DRFUX0mHkWiMukjgWdRoOOdzEU_RtSomQ3GCDB4Q

GET {{Student_Management_System_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AccessToken}}

###
GET {{Student_Management_System_HostAddress}}/weatherforecast/student
Accept: application/json
Authorization: Bearer {{AccessToken}}

###
GET {{Student_Management_System_HostAddress}}/weatherforecast/create-account?email=admin@example.com&role=ADMIN
Accept: application/json
Authorization: Bearer {{AccessToken}}
