ALTER TYPE enrollment_status ADD VALUE IF NOT EXISTS 'PENDING';

ALTER TABLE classrooms
ADD COLUMN IF NOT EXISTS age_group varchar(50),
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS capacity integer NOT NULL DEFAULT 20;
